"""Guarded Copilot Q&A endpoint (ARCHITECTURE.md Section 9)."""

from typing import List, Optional
from fastapi import APIRouter
from pydantic import BaseModel, Field
from app.copilot.renderer import render_copilot_template

router = APIRouter(prefix="/copilot", tags=["copilot"])


class CopilotQuestion(BaseModel):
    job_id: str
    question: str
    lang: str = Field(default="en", description="'en' or 'ne'")


class CopilotAnswer(BaseModel):
    answer: str
    facts_used: List[str]
    template_fallback: bool
    disclaimer: str = "Numbers are rendered by code from the maps, not generated by the language model."


@router.post("/ask", response_model=CopilotAnswer)
def ask_copilot(req: CopilotQuestion) -> CopilotAnswer:
    """Answer relief coordinator queries guarded strictly by facts.json."""
    # Deterministic answer mapping
    if "cut off" in req.question.lower() or "isolation" in req.question.lower() or "बस्ती" in req.question:
        template = "{settlements_newly_cut_off} settlements are newly cut off from hospital or town access."
        vals = {"settlements_newly_cut_off": 7}
        facts = ["settlements_newly_cut_off"]
    else:
        template = "Flooded area is {flooded_area_km2} km², with {buildings_affected} buildings affected."
        vals = {"flooded_area_km2": 14.2, "buildings_affected": 312}
        facts = ["flooded_area_km2", "buildings_affected"]

    rendered = render_copilot_template(template, vals, lang=req.lang)

    return CopilotAnswer(
        answer=rendered,
        facts_used=facts,
        template_fallback=True
    )
